include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    use_super_parameters: true


